import { ReactNode } from "react";
import "../globals.css";

import Header from "@/components/frontend/Header";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function FrontendLayout({ children, modal }: { children: ReactNode, modal: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        {modal}
      </body>
    </html>
  );
}